# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/flight-host/crazyflie-link-cpp-expanded

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/flight-host/crazyflie-link-cpp-expanded

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/flight-host/crazyflie-link-cpp-expanded/CMakeFiles /home/flight-host/crazyflie-link-cpp-expanded//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/flight-host/crazyflie-link-cpp-expanded/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cflinkcpp

# Build rule for target.
cflinkcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cflinkcpp
.PHONY : cflinkcpp

# fast build rule for target.
cflinkcpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cflinkcpp.dir/build.make CMakeFiles/cflinkcpp.dir/build
.PHONY : cflinkcpp/fast

#=============================================================================
# Target rules for targets named crazyflieLinkCpp

# Build rule for target.
crazyflieLinkCpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crazyflieLinkCpp
.PHONY : crazyflieLinkCpp

# fast build rule for target.
crazyflieLinkCpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/build
.PHONY : crazyflieLinkCpp/fast

#=============================================================================
# Target rules for targets named example_console

# Build rule for target.
example_console: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_console
.PHONY : example_console

# fast build rule for target.
example_console/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_console.dir/build.make CMakeFiles/example_console.dir/build
.PHONY : example_console/fast

#=============================================================================
# Target rules for targets named example_scan

# Build rule for target.
example_scan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_scan
.PHONY : example_scan

# fast build rule for target.
example_scan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_scan.dir/build.make CMakeFiles/example_scan.dir/build
.PHONY : example_scan/fast

#=============================================================================
# Target rules for targets named example_benchmark

# Build rule for target.
example_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_benchmark
.PHONY : example_benchmark

# fast build rule for target.
example_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_benchmark.dir/build.make CMakeFiles/example_benchmark.dir/build
.PHONY : example_benchmark/fast

#=============================================================================
# Target rules for targets named example_basicToc

# Build rule for target.
example_basicToc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_basicToc
.PHONY : example_basicToc

# fast build rule for target.
example_basicToc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_basicToc.dir/build.make CMakeFiles/example_basicToc.dir/build
.PHONY : example_basicToc/fast

#=============================================================================
# Target rules for targets named example_basicParam

# Build rule for target.
example_basicParam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_basicParam
.PHONY : example_basicParam

# fast build rule for target.
example_basicParam/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_basicParam.dir/build.make CMakeFiles/example_basicParam.dir/build
.PHONY : example_basicParam/fast

examples/basicParam.o: examples/basicParam.cpp.o

.PHONY : examples/basicParam.o

# target to build an object file
examples/basicParam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_basicParam.dir/build.make CMakeFiles/example_basicParam.dir/examples/basicParam.cpp.o
.PHONY : examples/basicParam.cpp.o

examples/basicParam.i: examples/basicParam.cpp.i

.PHONY : examples/basicParam.i

# target to preprocess a source file
examples/basicParam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_basicParam.dir/build.make CMakeFiles/example_basicParam.dir/examples/basicParam.cpp.i
.PHONY : examples/basicParam.cpp.i

examples/basicParam.s: examples/basicParam.cpp.s

.PHONY : examples/basicParam.s

# target to generate assembly for a file
examples/basicParam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_basicParam.dir/build.make CMakeFiles/example_basicParam.dir/examples/basicParam.cpp.s
.PHONY : examples/basicParam.cpp.s

examples/basicToc.o: examples/basicToc.cpp.o

.PHONY : examples/basicToc.o

# target to build an object file
examples/basicToc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_basicToc.dir/build.make CMakeFiles/example_basicToc.dir/examples/basicToc.cpp.o
.PHONY : examples/basicToc.cpp.o

examples/basicToc.i: examples/basicToc.cpp.i

.PHONY : examples/basicToc.i

# target to preprocess a source file
examples/basicToc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_basicToc.dir/build.make CMakeFiles/example_basicToc.dir/examples/basicToc.cpp.i
.PHONY : examples/basicToc.cpp.i

examples/basicToc.s: examples/basicToc.cpp.s

.PHONY : examples/basicToc.s

# target to generate assembly for a file
examples/basicToc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_basicToc.dir/build.make CMakeFiles/example_basicToc.dir/examples/basicToc.cpp.s
.PHONY : examples/basicToc.cpp.s

examples/benchmark.o: examples/benchmark.cpp.o

.PHONY : examples/benchmark.o

# target to build an object file
examples/benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_benchmark.dir/build.make CMakeFiles/example_benchmark.dir/examples/benchmark.cpp.o
.PHONY : examples/benchmark.cpp.o

examples/benchmark.i: examples/benchmark.cpp.i

.PHONY : examples/benchmark.i

# target to preprocess a source file
examples/benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_benchmark.dir/build.make CMakeFiles/example_benchmark.dir/examples/benchmark.cpp.i
.PHONY : examples/benchmark.cpp.i

examples/benchmark.s: examples/benchmark.cpp.s

.PHONY : examples/benchmark.s

# target to generate assembly for a file
examples/benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_benchmark.dir/build.make CMakeFiles/example_benchmark.dir/examples/benchmark.cpp.s
.PHONY : examples/benchmark.cpp.s

examples/console.o: examples/console.cpp.o

.PHONY : examples/console.o

# target to build an object file
examples/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_console.dir/build.make CMakeFiles/example_console.dir/examples/console.cpp.o
.PHONY : examples/console.cpp.o

examples/console.i: examples/console.cpp.i

.PHONY : examples/console.i

# target to preprocess a source file
examples/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_console.dir/build.make CMakeFiles/example_console.dir/examples/console.cpp.i
.PHONY : examples/console.cpp.i

examples/console.s: examples/console.cpp.s

.PHONY : examples/console.s

# target to generate assembly for a file
examples/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_console.dir/build.make CMakeFiles/example_console.dir/examples/console.cpp.s
.PHONY : examples/console.cpp.s

examples/scan.o: examples/scan.cpp.o

.PHONY : examples/scan.o

# target to build an object file
examples/scan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_scan.dir/build.make CMakeFiles/example_scan.dir/examples/scan.cpp.o
.PHONY : examples/scan.cpp.o

examples/scan.i: examples/scan.cpp.i

.PHONY : examples/scan.i

# target to preprocess a source file
examples/scan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_scan.dir/build.make CMakeFiles/example_scan.dir/examples/scan.cpp.i
.PHONY : examples/scan.cpp.i

examples/scan.s: examples/scan.cpp.s

.PHONY : examples/scan.s

# target to generate assembly for a file
examples/scan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_scan.dir/build.make CMakeFiles/example_scan.dir/examples/scan.cpp.s
.PHONY : examples/scan.cpp.s

src/Connection.o: src/Connection.cpp.o

.PHONY : src/Connection.o

# target to build an object file
src/Connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Connection.cpp.o
.PHONY : src/Connection.cpp.o

src/Connection.i: src/Connection.cpp.i

.PHONY : src/Connection.i

# target to preprocess a source file
src/Connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Connection.cpp.i
.PHONY : src/Connection.cpp.i

src/Connection.s: src/Connection.cpp.s

.PHONY : src/Connection.s

# target to generate assembly for a file
src/Connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Connection.cpp.s
.PHONY : src/Connection.cpp.s

src/ConnectionWrapper.o: src/ConnectionWrapper.cpp.o

.PHONY : src/ConnectionWrapper.o

# target to build an object file
src/ConnectionWrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/ConnectionWrapper.cpp.o
.PHONY : src/ConnectionWrapper.cpp.o

src/ConnectionWrapper.i: src/ConnectionWrapper.cpp.i

.PHONY : src/ConnectionWrapper.i

# target to preprocess a source file
src/ConnectionWrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/ConnectionWrapper.cpp.i
.PHONY : src/ConnectionWrapper.cpp.i

src/ConnectionWrapper.s: src/ConnectionWrapper.cpp.s

.PHONY : src/ConnectionWrapper.s

# target to generate assembly for a file
src/ConnectionWrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/ConnectionWrapper.cpp.s
.PHONY : src/ConnectionWrapper.cpp.s

src/CrazyflieUSB.o: src/CrazyflieUSB.cpp.o

.PHONY : src/CrazyflieUSB.o

# target to build an object file
src/CrazyflieUSB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyflieUSB.cpp.o
.PHONY : src/CrazyflieUSB.cpp.o

src/CrazyflieUSB.i: src/CrazyflieUSB.cpp.i

.PHONY : src/CrazyflieUSB.i

# target to preprocess a source file
src/CrazyflieUSB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyflieUSB.cpp.i
.PHONY : src/CrazyflieUSB.cpp.i

src/CrazyflieUSB.s: src/CrazyflieUSB.cpp.s

.PHONY : src/CrazyflieUSB.s

# target to generate assembly for a file
src/CrazyflieUSB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyflieUSB.cpp.s
.PHONY : src/CrazyflieUSB.cpp.s

src/CrazyflieUSBThread.o: src/CrazyflieUSBThread.cpp.o

.PHONY : src/CrazyflieUSBThread.o

# target to build an object file
src/CrazyflieUSBThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyflieUSBThread.cpp.o
.PHONY : src/CrazyflieUSBThread.cpp.o

src/CrazyflieUSBThread.i: src/CrazyflieUSBThread.cpp.i

.PHONY : src/CrazyflieUSBThread.i

# target to preprocess a source file
src/CrazyflieUSBThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyflieUSBThread.cpp.i
.PHONY : src/CrazyflieUSBThread.cpp.i

src/CrazyflieUSBThread.s: src/CrazyflieUSBThread.cpp.s

.PHONY : src/CrazyflieUSBThread.s

# target to generate assembly for a file
src/CrazyflieUSBThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyflieUSBThread.cpp.s
.PHONY : src/CrazyflieUSBThread.cpp.s

src/Crazyradio.o: src/Crazyradio.cpp.o

.PHONY : src/Crazyradio.o

# target to build an object file
src/Crazyradio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Crazyradio.cpp.o
.PHONY : src/Crazyradio.cpp.o

src/Crazyradio.i: src/Crazyradio.cpp.i

.PHONY : src/Crazyradio.i

# target to preprocess a source file
src/Crazyradio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Crazyradio.cpp.i
.PHONY : src/Crazyradio.cpp.i

src/Crazyradio.s: src/Crazyradio.cpp.s

.PHONY : src/Crazyradio.s

# target to generate assembly for a file
src/Crazyradio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Crazyradio.cpp.s
.PHONY : src/Crazyradio.cpp.s

src/CrazyradioThread.o: src/CrazyradioThread.cpp.o

.PHONY : src/CrazyradioThread.o

# target to build an object file
src/CrazyradioThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyradioThread.cpp.o
.PHONY : src/CrazyradioThread.cpp.o

src/CrazyradioThread.i: src/CrazyradioThread.cpp.i

.PHONY : src/CrazyradioThread.i

# target to preprocess a source file
src/CrazyradioThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyradioThread.cpp.i
.PHONY : src/CrazyradioThread.cpp.i

src/CrazyradioThread.s: src/CrazyradioThread.cpp.s

.PHONY : src/CrazyradioThread.s

# target to generate assembly for a file
src/CrazyradioThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/CrazyradioThread.cpp.s
.PHONY : src/CrazyradioThread.cpp.s

src/Param.o: src/Param.cpp.o

.PHONY : src/Param.o

# target to build an object file
src/Param.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Param.cpp.o
.PHONY : src/Param.cpp.o

src/Param.i: src/Param.cpp.i

.PHONY : src/Param.i

# target to preprocess a source file
src/Param.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Param.cpp.i
.PHONY : src/Param.cpp.i

src/Param.s: src/Param.cpp.s

.PHONY : src/Param.s

# target to generate assembly for a file
src/Param.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Param.cpp.s
.PHONY : src/Param.cpp.s

src/Toc.o: src/Toc.cpp.o

.PHONY : src/Toc.o

# target to build an object file
src/Toc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Toc.cpp.o
.PHONY : src/Toc.cpp.o

src/Toc.i: src/Toc.cpp.i

.PHONY : src/Toc.i

# target to preprocess a source file
src/Toc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Toc.cpp.i
.PHONY : src/Toc.cpp.i

src/Toc.s: src/Toc.cpp.s

.PHONY : src/Toc.s

# target to generate assembly for a file
src/Toc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Toc.cpp.s
.PHONY : src/Toc.cpp.s

src/USBDevice.o: src/USBDevice.cpp.o

.PHONY : src/USBDevice.o

# target to build an object file
src/USBDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/USBDevice.cpp.o
.PHONY : src/USBDevice.cpp.o

src/USBDevice.i: src/USBDevice.cpp.i

.PHONY : src/USBDevice.i

# target to preprocess a source file
src/USBDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/USBDevice.cpp.i
.PHONY : src/USBDevice.cpp.i

src/USBDevice.s: src/USBDevice.cpp.s

.PHONY : src/USBDevice.s

# target to generate assembly for a file
src/USBDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/USBDevice.cpp.s
.PHONY : src/USBDevice.cpp.s

src/USBManager.o: src/USBManager.cpp.o

.PHONY : src/USBManager.o

# target to build an object file
src/USBManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/USBManager.cpp.o
.PHONY : src/USBManager.cpp.o

src/USBManager.i: src/USBManager.cpp.i

.PHONY : src/USBManager.i

# target to preprocess a source file
src/USBManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/USBManager.cpp.i
.PHONY : src/USBManager.cpp.i

src/USBManager.s: src/USBManager.cpp.s

.PHONY : src/USBManager.s

# target to generate assembly for a file
src/USBManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/USBManager.cpp.s
.PHONY : src/USBManager.cpp.s

src/Version.o: src/Version.cpp.o

.PHONY : src/Version.o

# target to build an object file
src/Version.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Version.cpp.o
.PHONY : src/Version.cpp.o

src/Version.i: src/Version.cpp.i

.PHONY : src/Version.i

# target to preprocess a source file
src/Version.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Version.cpp.i
.PHONY : src/Version.cpp.i

src/Version.s: src/Version.cpp.s

.PHONY : src/Version.s

# target to generate assembly for a file
src/Version.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crazyflieLinkCpp.dir/build.make CMakeFiles/crazyflieLinkCpp.dir/src/Version.cpp.s
.PHONY : src/Version.cpp.s

src/python_bindings.o: src/python_bindings.cpp.o

.PHONY : src/python_bindings.o

# target to build an object file
src/python_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cflinkcpp.dir/build.make CMakeFiles/cflinkcpp.dir/src/python_bindings.cpp.o
.PHONY : src/python_bindings.cpp.o

src/python_bindings.i: src/python_bindings.cpp.i

.PHONY : src/python_bindings.i

# target to preprocess a source file
src/python_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cflinkcpp.dir/build.make CMakeFiles/cflinkcpp.dir/src/python_bindings.cpp.i
.PHONY : src/python_bindings.cpp.i

src/python_bindings.s: src/python_bindings.cpp.s

.PHONY : src/python_bindings.s

# target to generate assembly for a file
src/python_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cflinkcpp.dir/build.make CMakeFiles/cflinkcpp.dir/src/python_bindings.cpp.s
.PHONY : src/python_bindings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cflinkcpp"
	@echo "... crazyflieLinkCpp"
	@echo "... example_basicParam"
	@echo "... example_basicToc"
	@echo "... example_benchmark"
	@echo "... example_console"
	@echo "... example_scan"
	@echo "... examples/basicParam.o"
	@echo "... examples/basicParam.i"
	@echo "... examples/basicParam.s"
	@echo "... examples/basicToc.o"
	@echo "... examples/basicToc.i"
	@echo "... examples/basicToc.s"
	@echo "... examples/benchmark.o"
	@echo "... examples/benchmark.i"
	@echo "... examples/benchmark.s"
	@echo "... examples/console.o"
	@echo "... examples/console.i"
	@echo "... examples/console.s"
	@echo "... examples/scan.o"
	@echo "... examples/scan.i"
	@echo "... examples/scan.s"
	@echo "... src/Connection.o"
	@echo "... src/Connection.i"
	@echo "... src/Connection.s"
	@echo "... src/ConnectionWrapper.o"
	@echo "... src/ConnectionWrapper.i"
	@echo "... src/ConnectionWrapper.s"
	@echo "... src/CrazyflieUSB.o"
	@echo "... src/CrazyflieUSB.i"
	@echo "... src/CrazyflieUSB.s"
	@echo "... src/CrazyflieUSBThread.o"
	@echo "... src/CrazyflieUSBThread.i"
	@echo "... src/CrazyflieUSBThread.s"
	@echo "... src/Crazyradio.o"
	@echo "... src/Crazyradio.i"
	@echo "... src/Crazyradio.s"
	@echo "... src/CrazyradioThread.o"
	@echo "... src/CrazyradioThread.i"
	@echo "... src/CrazyradioThread.s"
	@echo "... src/Param.o"
	@echo "... src/Param.i"
	@echo "... src/Param.s"
	@echo "... src/Toc.o"
	@echo "... src/Toc.i"
	@echo "... src/Toc.s"
	@echo "... src/USBDevice.o"
	@echo "... src/USBDevice.i"
	@echo "... src/USBDevice.s"
	@echo "... src/USBManager.o"
	@echo "... src/USBManager.i"
	@echo "... src/USBManager.s"
	@echo "... src/Version.o"
	@echo "... src/Version.i"
	@echo "... src/Version.s"
	@echo "... src/python_bindings.o"
	@echo "... src/python_bindings.i"
	@echo "... src/python_bindings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

